### ISSUE TITLE
Build a Webhook for a Chatbot using Python

### ISSUE THREAD

**Issue by SaravanaKumarVelliyangiri** [SAPDocuments/Issues#13]
Tutorial: https://developers.sap.com/tutorials/conversational-ai-webhook-script-python.html
--------------------------

Write here what you need help with step 5.

The app crashes when it's pushed to cloud foundry

**Comment by thecodester** [comment]
Can you provide more details: what command did you run, what error message is displayed, what was done by the user, and so forth ...

**Comment by thecodester** [comment]
I also had trouble. I did the following:
- Changed the runtime to 3.8.5
- Changed the manifest to this:

```
applications:
- name: myapp
  host: dbw-catfacts
  path: .
  memory: 128M
  command: python chatbot-webhook-test.py
```

I need to experiment what parts of this manifest.yml I really need. It is described here: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/aef3e030b6494f6a82dc6e7ea94c93fa.html

Both of these things are required. At the same time I created a quote plan for my subaccount and used it for my space. I assume this was also necessary, but not sure exactly what is needed.

I will update tutorial.

**Comment by thecodester** [comment]
It seems to me you need the proper runtime, and the manifest.yml to have at least this:

```
applications:
- host: dbw-catfacts
  memory: 128M
  command: python chatbot-webhook-test.py
```

Your host has to be unique in the CF endpoint. I guess they no longer automatically create an route for you and you have to specify a host.

It did not seem to matter if I set up entitlements or quota -- I think the default subaccount and space in a trial account has quota/entitlements built in.

Tell me if you are able to deploy.
