### ISSUE TITLE
Create a User Interface with CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Issues#264]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-ui.html
--------------------------

Once completed this step (as well as the following authentication step) I find that I cannot build the MTA without it going into an infinite loop and using up all the disk space in my BAS workspace.

To be able to build the MTA I had to add this to the ui deployer module:
```
build-parameters:
      ignore: [".*/"]
```

Now that I have a built MTA if I try and deploy it, it fails on the ui deployer.

```
Error uploading content module "MyHANAApp_ui_deployer" in service "MyHANAApp_html_repo_host" /// + heaps more
```

When I look at the ui deployer module in the mat file I see this:

```
  - name: MyHANAApp_ui_deployer
    type: com.sap.application.content
    path: .
    requires:
      - name: MyHANAApp_html_repo_host
        parameters:
          content-target: true
    build-parameters:
      ignore: [".*/"]
```

This does not seem right to me. It missing the bit about what .zip file to pick up that contains the built app? I have re-done the tutorial a second time and got exactly the same result. Any ideas what I could be doing wrong?
I also cant see any ui5 tooling yaml file which build the Fiori app?

Thanks, Jason.
