### ISSUE TITLE
Add the SAP Launchpad Service - Step 10 will fail

### ISSUE THREAD

**Issue by sqjlin** [SAPDocuments/Issues#501]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

Step 10 will fail because of MTA.yaml file.
Error message:
Telemetry]: ENOENT: no such file or directory, open
[Telemetry]: ENOENT: no such file or directory, open
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: the "/Users/XXXXX/Documents/btpapptutorial/cpapp/mta.yaml" file is not a valid MTA descriptor: yaml: unmarshal errors:
  line 132: field build-parameters not found in type mta.Resource
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@sap/generator-fiori/generators/commonlibs/index.js:2:822884)
    at ChildProcess.emit (events.js:375:28)
    at ChildProcess.emit (domain.js:470:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/@sap/generator-fiori/node_modules/yeoman-generator/lib/index.js:791:20)
    at processImmediate (internal/timers.js:464:21)

I managed to overcome this issue by copying the MTA.yaml file content from launchpad-service branch
https://raw.githubusercontent.com/SAP-samples/cloud-cap-risk-management/launchpad-service/mta.yaml

**Comment by uwe-klinger** [comment]
Hi @sqjlin,

The block `cpapp-destinations` (with the "s" at the end) is in the `modules` section of the `mta.yaml`. I think you put it accidentially in the `resources` section. This leads to this error message.

```yaml 
- name: cpapp-destinations
  type: com.sap.application.content
  requires:
  - name: cpapp-uaa
    parameters:
      service-key:
        name: cpapp-uaa-key
  - name: cpapp-html5-repo-host
    parameters:
      service-key:
        name: cpapp-html5-repo-host-key
  - name: srv-api
  - name: cpapp-destination
    parameters:
      content-target: true
  parameters:
    content:
      instance:
        destinations:
        - Authentication: OAuth2UserTokenExchange
          Name: cpapp-app-srv
          TokenServiceInstanceName: cpapp-uaa
          TokenServiceKeyName: cpapp-uaa-key
          URL: ~{srv-api/srv-url}
          sap.cloud.service: cpapp.service
        - Name: cpapp-html5-repo-host
          ServiceInstanceName: cpapp-html5-repo-host
          ServiceKeyName: cpapp-html5-repo-host-key
          sap.cloud.service: cpapp.service
        - Authentication: OAuth2UserTokenExchange
          Name: cpapp-uaa
          ServiceInstanceName: cpapp-uaa
          ServiceKeyName: cpapp-uaa-key
          sap.cloud.service: cpapp.service
        existing_destinations_policy: update
  build-parameters:
    no-source: true
```

The `cpapp-destination` (without the "s") should stay in `resources`.

```yaml
- name: cpapp-destination
  type: org.cloudfoundry.managed-service
  parameters:
    config:
      HTML5Runtime_enabled: true
      init_data:
        instance:
          destinations:
          - Authentication: NoAuthentication
            Name: ui5
            ProxyType: Internet
            Type: HTTP
            URL: https://ui5.sap.com
          existing_destinations_policy: update
      version: 1.0.0
    service: destination
    service-plan: lite
```

We will check if we can make the naming clearer.
