### ISSUE TITLE
Create a Reusable Service - error in application.yml

### ISSUE THREAD

**Issue by glageb** [SAPDocuments/Issues#570]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

Hi

The step 6 in this tutorial is leading to wrong parameters in application.yml. After investigating the issues and doing changes in yml file, the following one worked nicely. I think documentation needs to be updated.

Thank you

Guilherme

`---
spring:
  profiles: spring.config.activate.on-profile
  datasource:
    url: "jdbc:sqlite:/home/user/projects/products-service/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: never
`

**Comment by iwonahahn** [comment]
Hi @glageb,

Sorry for the late reply, I was on vacation. I need to sync with the dev colleagues and will get back to you asap.

Best regards,
Iwona

**Comment by mofterdinger** [comment]
Hi,
I don't think the provided application.yaml above is correct, it should be:
```yaml
---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/products-service/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
```

@glageb What do you think ?

Thanks,
Markus
